version: '3.8'

x-airflow-common: &airflow-common
  # Build a custom image from the Dockerfile in the current directory
  build: .
  env_file:
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    # Mount the dbt project so Airflow can run dbt commands
    - ./dbt_sap_transformations:/opt/airflow/dbt
    # Mount the source data so Airflow can access it
    - ./sap_mock_data:/opt/airflow/data
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    container_name: sap_project_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: sap_project_scheduler
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname \"$${HOSTNAME}\""]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    container_name: sap_project_webserver
    command: webserver
    ports:
      - "8084:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8084/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: sap_project_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Anonymous \
          --lastname User \
          --role Admin \
          --email admin@example.org

volumes:
  postgres_db_volume: